#!/bin/sh
#
# 3/10/98 Get a web page that gets local state every hour to keep cache "fresh"
#
while [ 1 ]; do


cat<<END | perl
use LWP::Simple;
get("http://www.seva.net/~msolomon/wx/wx.cgi");
END

# Sleep for a hour
sleep 3600 

done
